# Change these first
owner: scrappy762 # Your GitHub organization or username, where this repository lives
repo: server-status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: TMD 17-2148 (CD J6)
    url: $http://166.155.41.117
    method: POST
  - name: TMD 17-2155 Laredo HITDA
    url: $http://166.141.87.55
    method: POST
  - name: TMD 17-2149 LC 15-0562
    url: $http://166.155.42.143
    method: POST
  - name: TMD 17-2164 
    url: $http://166.155.42.145
    method: POST
  - name: TMD 17-2160
    url: $http://166.155.42.200
    method: POST
  - name: TMD 17-2161 (GRD Team Room)
    url: $http://166.155.54.134
    method: POST
  - name: TMD 17-2131
    url: $http://166.155.41.155
    method: POST
  - name: TMD 17-2168
    url: $http://166.155.42.199
    method: POST
  - name: TMD 17-2167
    url: $http://166.155.41.125
    method: POST
  - name: TMD 17-2175
    url: $http://166.155.42.149
    method: POST
  - name: TMD 17-2173
    url: $http://166.155.42.202
    method: POST
  - name: TMD 17-2133
    url: $http://166.155.41.224
    method: POST
  - name: TMD 17-2134
    url: $http://166.155.41.153
    method: POST
  - name: TMD 17-2137
    url: $http://166.155.42.201
    method: POST
  - name: TMD 17-2146
    url: $http://166.155.41.127
    method: POST
  - name: TMD 17-2162
    url: $http://166.155.41.208
    method: POST
  - name: TMD 17-2156
    url: $http://166.155.41.226
  - name: Test Broken Site
    url: $https://thissitedoesnotexist.koj.co

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /server-status
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GRD Device Status
  introTitle: "**Upptime** is the live status of JCDTF-GR deployed devices"
  introMessage: This page displays GRD device status in real time

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
